USE SCHEMA DEMO1.PUBLIC;
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (1, 'Crista', 'Mynard', 'cmynard0@eepurl.com', 'Female', '240.11.149.225');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (2, 'Vincents', 'Digle', 'vdigle1@nymag.com', 'Male', '187.21.77.167');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (3, 'Debee', 'Ozanne', 'dozanne2@microsoft.com', 'Female', '15.148.241.118');